"""
Qualis Tender Hunter — Keyword Configuration v2
================================================
Major precision overhaul — Session 6 performance analysis identified:
  - 42% false positive rate (furniture, lab equipment, road maintenance)
  - "supply and install" + "commissioning" firing on everything
  - Missing high-value signals: mini-grid, LV/MV distribution, emergency power

Changes vs v1:
  REMOVED from SOFT: "supply and install", "commissioning", "design and build",
                     "electrical" (alone), "electric" (alone)  - all too generic
  ADDED to STRONG: electrical installation, power supply system, mini-grid,
                   LV/MV distribution, off-grid solar, emergency power, etc.
  ADDED to HARD_EXCLUDE: laboratory equipment, vaccine, office furniture,
                          medical equipment, filling machine, dental/x-ray
  EXPANDED PRIORITY_BUYERS: TANESCO, TANROADS, REA, NHC, TPA, TAZARA added
"""

# STRONG SIGNALS - unmistakably Qualis work. Score +10 each.
STRONG_INCLUDE = [
    # Core electrical contracting (CRB Class V)
    "electrical installation",
    "electrical install",
    "electrical work",
    "electrical system",
    "electrical maintenance",
    "electrical fittings",
    "electrical materials",
    "electrical contractor",
    "power installation",
    "power supply system",
    "supply and installation of electrical",
    "installation of electrical",
    # Solar - all variants
    "solar pv",
    "solar system",
    "solar streetlight",
    "solar street light",
    "solar installation",
    "solar panel",
    "photovoltaic",
    "off-grid solar",
    "on-grid solar",
    "installation of solar",
    # Grid-scale / off-grid power
    "mini-grid",
    "mini grid",
    "microgrid",
    "micro grid",
    # Generators / backup power
    "generator supply",
    "generator install",
    "generator maintenance",
    "standby generator",
    "diesel generator",
    "genset",
    "emergency generator",
    "emergency power supply",
    "emergency lighting system",
    # High / medium / low voltage infrastructure
    "33kv",
    "11kv",
    "0.4kv",
    "substation",
    "transformer install",
    "transformer supply",
    "transformer replacement",
    "power line",
    "transmission line",
    "distribution line",
    "lv distribution",
    "mv distribution",
    "overhead line",
    "underground cable",
    "hv cable",
    "mv cable",
    "lv cable",
    # UPS / power conditioning
    "ups system",
    "uninterruptible power",
    "uninterrupted power",
    "battery backup system",
    "automatic voltage regulator",
    "avr",
    # Hose division (Qualis hose business)
    "hydraulic hose",
    "pneumatic hose",
    "hose repair",
    "hose assembly",
    "hose supply",
    "industrial hose",
    # Building materials (Qualis supply division)
    "cement supply",
    "supply of cement",
    "supply of bricks",
    "steel supply",
    "supply of steel",
    "building materials",
    "supply of building materials",
    "reinforcement steel",
    "roofing materials",
    # Full supply-install packages specific to Qualis scope
    "supply, installation, testing and commissioning",
    "supply install test commission",
    "design, supply and installation",
    "design supply install",
    "installation of generator",
    "installation of ups",
    "installation of solar",
]

# SOFT SIGNALS - relevant but not definitive. Score +2 each.
# RULE: Only include if they don't routinely fire on non-Qualis sectors.
# REMOVED: "supply and install", "commissioning", "electrical" alone, "electric" alone
SOFT_INCLUDE = [
    "solar",
    "generator",
    "genset",
    "ups",
    "substation",
    "transformer",
    "lighting",
    "streetlight",
    "street light",
    "floodlight",
    "hose",
    "hydraulic",
    "pneumatic",
    "switchgear",
    "cabling",
    "wiring",
    "panel board",
    "distribution board",
    "mdb",
    "hvac",
    "air conditioning",
    "ict installation",
    "structured cabling",
    "armoured cable",
    "conduit",
    "earthing",
    "grounding",
    "power factor",
    "load bank",
    "automatic transfer switch",
    "ats",
]

# HARD EXCLUSIONS - kill any match immediately.
HARD_EXCLUDE = [
    # Lab / scientific / medical (NOT electrical contracting)
    "laboratory equipment",
    "lab equipment",
    "laboratory furniture",
    "laboratory chemicals",
    "laboratory reagents",
    "scientific equipment",
    "medical equipment",
    "medical supplies",
    "medical devices",
    "pharmaceutical",
    "medicine supply",
    "supply of medicine",
    "vaccine",
    "filling machine",
    "dental equipment",
    "dental chair",
    "x-ray",
    "xray",
    "autoclave",
    "centrifuge",
    "microscope",
    "ultrasound",
    "dialysis",
    # Furniture (NOT Qualis)
    "office furniture",
    "furniture supply",
    "supply of furniture",
    "supply and installation of furniture",
    "chairs and tables",
    "classroom furniture",
    "hospital furniture",
    "school furniture",
    # Food & hospitality
    "catering service",
    "food supply",
    "outside catering",
    "accommodation service",
    "hotel service",
    "tea and coffee",
    "supply of food",
    # Pure professional services
    "legal service",
    "legal counsel",
    "legal advisor",
    "advocate service",
    "translation service",
    "interpretation service",
    "consultancy service",
    "consulting service",
    "advisory service",
    "feasibility study",
    "needs assessment",
    "baseline survey",
    "environmental impact",
    "audit service",
    "financial service",
    "insurance service",
    "actuarial",
    # Stationery / printing
    "printing service",
    "stationery supply",
    "supply of stationery",
    "office supplies",
    "managed print",
    "supply of paper",
    "toner cartridge",
    # Pure transport / fleet
    "car hire",
    "vehicle hire",
    "fleet supply",
    "rental of vehicle",
    "fuel supply",
    "supply of fuel",
    "lubricant supply",
    "supply of tyres",
    # Training / capacity building
    "training service",
    "training program",
    "capacity building",
    "workshop facilitation",
    # Security guard (not electronic security)
    "security guard",
    "security service personnel",
    "manned guarding",
    # Cleaning / sanitation
    "cleaning service",
    "janitorial",
    "fumigation",
    "pest control",
    "waste management service",
    "garbage collection",
    # Land / property
    "lease of land",
    "lease of space",
    "lease of office",
    "land survey",
    "land valuation",
    # Software / ICT services (not installation)
    "software development",
    "software license",
    "erp implementation",
    "website development",
    "mobile application",
    "data entry",
    "it support service",
    # Agriculture / livestock
    "seeds supply",
    "supply of seeds",
    "fertilizer supply",
    "livestock supply",
    "animal feed",
    "veterinary supplies",
]

EXCLUDE_PROCUREMENT_METHODS = [
    "direct procurement",
]

OPERATING_REGIONS = [
    "dar es salaam", "mwanza", "mbeya", "iringa", "tabora", "arusha",
    "dodoma", "bagamoyo", "mkuranga", "morogoro", "kilimanjaro", "tanga",
    "mtwara", "ruvuma", "shinyanga", "singida", "kagera", "geita", "njombe",
    "rukwa", "katavi", "manyara", "songwe", "simiyu", "kigoma", "mara",
    "pwani", "lindi",
]

# PRIORITY BUYERS - existing clients + major infrastructure procurers.
# Case-insensitive substring match on buyer name from NeST.
PRIORITY_BUYERS = [
    # Existing Qualis clients (relationship = competitive edge)
    "bank of tanzania",
    "oryx energies",
    "backlite media",
    "marie stopes",
    "azan logistics",
    "starlite media",
    "knauf gypsum",
    "imed",
    "toyota tanzania",
    "karimjee",
    "shinyanga municipal council",
    "emirate aluminium",
    "emirates aluminium",
    "fresh spring fellowship",
    "alliance one tobacco",
    "tanzania breweries",
    "tbl mwanza",
    "cater & cure",
    "cater and cure",
    "karibu tanzania",
    "emirates glass",
    "kapa manufacturing",
    "sido",
    "small industries development organisation",
    "ghl farm park",
    # Major infrastructure procurers - high-value electrical tenders
    "tanesco",
    "tanzania electric supply",
    "rural energy agency",
    "tanroads",
    "tanzania national roads",
    "dawasa",
    "dar es salaam water",
    "tanzania ports authority",
    "tazara",
    "tanzania railways",
    "national housing corporation",
    "nssf",
    "psssf",
    "ppf pensions",
    "temesa",
    "tpdc",
    "pura",
    "tanapa",
    "ttcl",
]
